services:
  grafana:
    image: grafana/otel-lgtm:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
      - "3000:3000"   # Grafana UI
      - "4317:4317"   # OTLP/gRPC
      - "4318:4318"   # OTLP/HTTP
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - grafana-network

volumes:
  grafana-data:

networks:
  grafana-network:
    external: true
    name: shared-network
