services:
  rabbitmq-4:
    image: rabbitmq:4-management
    container_name: rabbitmq-4
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672" # AMQP 端口
      - "15672:15672" # 管理插件 Web UI 端口
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
