services:
  redis:
    image: redis:8
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --requirepass P@88w0rd
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru

volumes:
  redis-data:
